dist: trusty
language: ruby

git:
  depth: 1


cache:
  bundler: true
  directories:
  - $HOME/.cache/.htmlproofer

install:
  - git clone https://github.com/neomutt/neomutt.github.io
  - gem install jekyll
  - apt install expect-dev
  - gem install jekyll-gist
  - gem install jekyll-sitemap
  - gem install jekyll-mentions
  - gem install html-proofer
  - gem install jekyll-algolia

script:
    - mkdir -p _site/code/; touch _site/code/index.html
    - unbuffer jekyll build
    - http_status=({100..399});
    - unbuffer \ #maybe https://unix.stackexchange.com/a/25378 is better?
      htmlproofer \ 
      --http-status-ignore ${printf '%s,' "${http_status[@]}"} \
      --assume-extension \
      ./_site/**/*.{html,md}

