dist: trusty
language: ruby

git:
  depth: 1


cache: 
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
  - $TRAVIS_BUILD_DIR/neomutt/neomutt.github.io/code
  - ~/.rvm # contains rubygems

install:
  - git clone https://github.com/neomutt/neomutt.github.io
  - gem install jekyll
  - gem install jekyll-gist
  - gem install jekyll-sitemap
  - gem install jekyll-mentions
  - gem install html-proofer
  - gem install jekyll-algolia

before_script:
    - export -f travis_nanoseconds
    - export -f travis_fold
    - export -f travis_time_start
    - export -f travis_time_finish
script:
    - travis_fold start "used bash script" 
    -  cat ./.test.sh; 
    - travis_fold end "used bash script"
    - ./.test.sh
